name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/arm64]
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker pull kasmweb/remnux-focal-desktop:1.14.0
    - name: checkpath
      run: pwd
      
