name: Free Disk Space (Ubuntu)
on: push

jobs:
  free-disk-space:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: pwd
        run: pwd
      - name: ls
        run: ls -ahl ${{ github.workspace }}
      - name: before
        run: sudo chmod a+rwx ${{ github.workspace }}/free.sh && ${{ github.workspace }}/free.sh before.txt
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - name: after
        run: sudo chmod a+rwx ${{ github.workspace }}/free.sh && ${{ github.workspace }}/free.sh after.txt
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: ${{ github.workspace }}/*.txt
          compression-level: 9 # max compression