name: Docker Image To tar

on:
  push:
    tags:
      - "tar*"
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/arm64]
        os: [ ubuntu-latest ]
        arch: [ arm64 ]
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker pull kasmweb/remnux-focal-desktop:1.14.0
    - name: saveSpace
      run: rm -rf /opt/hostedtoolcache
    - name: checkpath
      run: ls -ahl && dh -a
    - name: clean
      run: sudo rm -rf /usr/share/dotnet && sudo rm -rf /opt/ghc && sudo rm -rf "/usr/local/share/boost" && sudo rm -rf "$AGENT_TOOLSDIRECTORY"
    - name: export
      run: docker save kasmweb/remnux-focal-desktop:1.14.0 -o remnux-focal-desktop-for-arm64.tar
    - name: checkpath
      run: ls -ahl && dh -a
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: remnux-focal-desktop
        path: ${{ github.workspace }}/remnux-focal-desktop-for-arm64.tar
        compression-level: 9 # max compression
